params:
  nb_epoch: 100

grid_params:
  batch_size:
    - 200
    - 100
    - 50
  learning_rate:
    - 0.0000001
    - 0.000001
    - 0.00005
  attention:
    - True
    - False
  dropout:
    -
    - 0.2
