params:
  nb_epoch: 50

grid_params:
  batch_size:
    - 30
    - 20
    - 10
  learning_rate:
    - 0.000001
    - 0.00005
    - 0.0005
  attention:
    - True
    - False
  dropout:
    -
    - 0.2
