params:
  nb_epoch: 50

grid_params:
  batch_size:
    - 30
    - 20
    - 10
  learning_rate:
    - 0.000001
    - 0.00005
    - 0.0005
  n_kernels:
    - 200
    - 100
  kernel_size:
    - 3
    - 2
    - 1
  attention:
    - True
    - False
  dropout:
    -
    - 0.2
