params:
  batch_size: 5
  learning_rate: 0.0001
  nb_epoch: 100

grid_params:
  batch_size:
    - 30
    - 20
    - 10
    - 5
  learning_rate:
    - 0.0001
    - 0.00001
    - 0.000005
    - 0.000001
  dropout:
    -
    - 0.2