params:
  batch_size: 5
  nb_epoch: 100

grid_params:
  batch_size:
    - 200
    - 100
    - 50
    - 30
  learning_rate:
    - 0.000005
    - 0.000001
    - 0.0000001
    - 0.00000001
  dropout:
    -
    - 0.2
