params:
  nb_epoch: 100
  n_kernels: 400

grid_params:
  batch_size:
    - 200
    - 100
    - 50
  learning_rate:
    - 0.0000001
    - 0.000001
    - 0.00005
  kernel_size:
    - 3
    - 2
    - 1
  attention:
    - True
    - False
  dropout:
    -
    - 0.2
