params:
  nthread: 8
  n_estimators: 300

grid_params:
  min_child_weight:
    - 1
    - 10
    - 20
  learning_rate:
    - 0.01
    - 0.1
    - 0.5
  max_depth:
    - 1
    - 2
    - 4
  subsample:
    - 0.8
    - 1.0
  colsample_bytree:
    - 0.5
    - 0.8
    - 1.0
