params:
  learning_rate: 0.3
  max_depth: 6
  min_child_weight: 1
  nthread: 8
  n_estimators: 150

grid_params:
  n_estimators:
    - 300
    - 200
    - 100
  max_depth:
    - 1
    - 2
    - 3
    - 4
    - 5
  subsample:
    - 0.5
    - 0.8
    - 1.0
  colsample_bytree:
    - 0.3
    - 0.5
    - 0.8
    - 1.0
